include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    always_declare_return_types: error
    invalid_annotation_target: ignore

  exclude:
    - lib/generated
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
    - lib/**/*.mocks.dart
    - test/**/*.mocks.dart

linter:
  rules:
    - require_trailing_commas
